課題1,2の実装
tatsuo-yamamoto-lvgs/HTTP-Cookie pull request #1
Opened 2024-01-11 12:00 UTC by tatsuo-yamamoto-lvgs

# 実装内容
- httpモジュールを使ってHTTP通信ができる
- リクエストヘッダーからクッキーヘッダーを読み取る
- リクエストにセッションIDがなければ、レスポンスにセッションIDを記載したSet-Cookieヘッダーを付与する
# レビュー観点
- コメントで書かれているところが適切か
- webエンジニアとしてやっていく中でコメントの理解の深さで十分そうか
# 備考
Cookieヘッダーの属性っていっぱいある中で、自分のサーバがセッションIDしか与えないのに、全て解析するのも変かなと思って、Cookieを読み取るだけで終えました。

2024-01-16 10:04 UTC, nonaka-shu-lvgs requested changes
課題１ができていないですね。やり直し

2024-01-16 10:04 UTC, nonaka-shu-lvgs commented on server/server.ts
> +const sessionId: string = generateSessionId(20);
✕

2024-01-22 04:00 UTC, nonaka-shu-lvgs commented on server/server.ts
> +const sessionId: string = generateSessionId(20);
このセッションIDの発番はだめです。なぜだめか考えてください

2024-01-22 08:44 UTC, tatsuo-yamamoto-lvgs commented on server/server.ts
> +const sessionId: string = generateSessionId(20);
同じSIDしか出なくなっちゃうからですね（笑）
変更しました！

2024-01-22 10:33 UTC, nonaka-shu-lvgs approved these changes

2024-01-22 12:01 UTC, merged